# Numpy入门

In [1]:
import numpy as np

In [4]:
d1 = np.arange(15).reshape(3,5)
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

维数`ndim`,几乘几的矩阵`shape`

In [5]:
d1.shape

(3, 5)

In [6]:
d1.ndim

2

In [7]:
d1.size

15

In [8]:
d1.dtype

dtype('int32')

In [9]:
d1.dtype.name

'int32'

In [10]:
type(d1)

numpy.ndarray

In [11]:
d2=np.array([6,7,8])
d2

array([6, 7, 8])

In [12]:
type(d2)

numpy.ndarray

In [15]:
d2.dtype

dtype('int32')

## 1.创建ndarray：有很多方法

### array:list-like

In [16]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
a.ndim

1

In [18]:
b = np.array((1,2,3))
b

array([1, 2, 3])