# Numpy入门

In [2]:
import numpy as np

In [4]:
d1 = np.arange(15).reshape(3,5)
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

维数`ndim`,几乘几的矩阵`shape`

In [5]:
d1.shape

(3, 5)

In [6]:
d1.ndim

2

In [7]:
d1.size

15

In [8]:
d1.dtype

dtype('int32')

In [9]:
d1.dtype.name

'int32'

In [10]:
type(d1)

numpy.ndarray

In [11]:
d2=np.array([6,7,8])
d2

array([6, 7, 8])

In [12]:
type(d2)

numpy.ndarray

In [15]:
d2.dtype

dtype('int32')

## 1.创建ndarray：有很多方法

### array:list-like

In [16]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
a.ndim

1

In [18]:
b = np.array((1,2,3))
b

array([1, 2, 3])

In [20]:
c = np.array([[1.5, 2., 3.],
             [4., 5., 6.]])
c

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [23]:
np.array([1,1.,3.]).dtype

dtype('float64')

In [24]:
d = np.array([[1,2],[3,4]], dtype=complex)
d

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

#### 零矩阵、一矩阵、空矩阵

In [27]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [29]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [30]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [32]:
np.ones([3,3],dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [34]:
np.empty([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

#### arange:类似于R中的seq

In [38]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [40]:
seq=np.arange(0,0.2,0.01)
seq

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19])

In [41]:
seq.shape  #只有一维

(20,)

In [42]:
seq.ndim  

1

#### linspace

In [43]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

#### zeros_like, ones_like, eye

In [45]:
np.zeros_like(a)

array([0, 0, 0])

In [46]:
np.ones_like(b)

array([1, 1, 1])

In [50]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## printing arrays

In [51]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [52]:
a

array([0, 1, 2, 3, 4, 5])

In [53]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## ndarray的基本操作

In [54]:
a = np.array( [20,30,40,50] )
b = np.arange(4)

In [55]:
a-b

array([20, 29, 38, 47])

In [56]:
b ** 2

array([0, 1, 4, 9])

In [58]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

##### 矩阵乘法需要使用dot,*指的是点乘

In [61]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A

array([[1, 1],
       [0, 1]])

In [62]:
B

array([[2, 0],
       [3, 4]])

In [63]:
A * B

array([[2, 0],
       [0, 4]])

In [64]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [65]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [66]:
np.dot(B,A)

array([[2, 2],
       [3, 7]])

##### modify 而不是copy

In [71]:
a

array([180, 270, 360, 450])

In [72]:
a *= 3
a

array([ 540,  810, 1080, 1350])

In [73]:
b

array([0, 1, 2, 3])

In [74]:
b += a
b

array([ 540,  811, 1082, 1353])

In [78]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [81]:
b.sum(axis=1)

array([ 6, 22, 38])

In [82]:
b.min(axis=0)

array([0, 1, 2, 3])

### Universal Functions

In [84]:
B = np.arange(3)
B

array([0, 1, 2])

In [85]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [86]:
np.sin(B)

array([ 0.        ,  0.84147098,  0.90929743])

In [87]:
np.round(B)

array([0, 1, 2])

### index
需要注意的一点就是numpy操作都是modify，要想不在原对象上进行修改，可以使用copy()
#### 一维

In [90]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [91]:
a[2]

8

In [92]:
a[2:4]

array([ 8, 27], dtype=int32)

In [93]:
a[:8:2]

array([  0,   8,  64, 216], dtype=int32)

In [95]:
a[::-1]  #逆序

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [97]:
a[0]=100
a

array([100,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

#### 多维

In [99]:
def f(x,y):
     return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [100]:
b[0:2,1:3]

array([[ 1,  2],
       [11, 12]])

In [101]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [102]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [104]:
b[-1]

array([40, 41, 42, 43])

## Shape Manipulation

In [4]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 3.,  5.,  0.,  2.],
       [ 7.,  4.,  6.,  2.],
       [ 5.,  0.,  9.,  8.]])

In [5]:
a.ravel()  

array([ 3.,  5.,  0.,  2.,  7.,  4.,  6.,  2.,  5.,  0.,  9.,  8.])

In [7]:
a.shape=(6,2)
a

array([[ 3.,  5.],
       [ 0.,  2.],
       [ 7.,  4.],
       [ 6.,  2.],
       [ 5.,  0.],
       [ 9.,  8.]])

In [8]:
a.T

array([[ 3.,  0.,  7.,  6.,  5.,  9.],
       [ 5.,  2.,  4.,  2.,  0.,  8.]])

In [10]:
a.resize((2,6))
a

array([[ 3.,  5.,  0.,  2.,  7.,  4.],
       [ 6.,  2.,  5.,  0.,  9.,  8.]])

In [11]:
a.reshape(3,-1)

array([[ 3.,  5.,  0.,  2.],
       [ 7.,  4.,  6.,  2.],
       [ 5.,  0.,  9.,  8.]])

In [12]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
a

array([[ 4.,  1.],
       [ 0.,  6.]])

In [13]:
b

array([[ 0.,  5.],
       [ 4.,  3.]])

In [15]:
np.vstack((a,b)) #vertical

array([[ 4.,  1.],
       [ 0.,  6.],
       [ 0.,  5.],
       [ 4.,  3.]])

In [16]:
np.hstack((a,b))

array([[ 4.,  1.,  0.,  5.],
       [ 0.,  6.,  4.,  3.]])

In [17]:
from numpy import newaxis
np.column_stack((a,b))

array([[ 4.,  1.,  0.,  5.],
       [ 0.,  6.,  4.,  3.]])

In [18]:
a = np.array([4.,2.])
b = np.array([2.,8.])
a[:,newaxis]

array([[ 4.],
       [ 2.]])

In [19]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [20]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

## Splitting one array into several smaller ones

In [21]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 5.,  3.,  2.,  9.,  0.,  5.,  7.,  6.,  3.,  0.,  7.,  9.],
       [ 2.,  4.,  6.,  2.,  3.,  9.,  4.,  5.,  9.,  5.,  1.,  4.]])

In [22]:
np.hsplit(a,3)

[array([[ 5.,  3.,  2.,  9.],
        [ 2.,  4.,  6.,  2.]]), array([[ 0.,  5.,  7.,  6.],
        [ 3.,  9.,  4.,  5.]]), array([[ 3.,  0.,  7.,  9.],
        [ 9.,  5.,  1.,  4.]])]

In [23]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 5.,  3.,  2.],
        [ 2.,  4.,  6.]]), array([[ 9.],
        [ 2.]]), array([[ 0.,  5.,  7.,  6.,  3.,  0.,  7.,  9.],
        [ 3.,  9.,  4.,  5.,  9.,  5.,  1.,  4.]])]

## Copies and Views

### View or Shallow Copy

In [24]:
a.view()

array([[ 5.,  3.,  2.,  9.,  0.,  5.,  7.,  6.,  3.,  0.,  7.,  9.],
       [ 2.,  4.,  6.,  2.,  3.,  9.,  4.,  5.,  9.,  5.,  1.,  4.]])

In [26]:
c=a.view()
c

array([[ 5.,  3.,  2.,  9.,  0.,  5.,  7.,  6.,  3.,  0.,  7.,  9.],
       [ 2.,  4.,  6.,  2.,  3.,  9.,  4.,  5.,  9.,  5.,  1.,  4.]])

In [28]:
c.base is a  # c是a中data的一个view

True

In [32]:
c.shape = 6,4
c

array([[ 5.,  3.,  2.,  9.],
       [ 0.,  5.,  7.,  6.],
       [ 3.,  0.,  7.,  9.],
       [ 2.,  4.,  6.,  2.],
       [ 3.,  9.,  4.,  5.],
       [ 9.,  5.,  1.,  4.]])

In [33]:
a.shape

(2, 12)

In [34]:
a

array([[ 5.,  3.,  2.,  9.,  0.,  5.,  7.,  6.,  3.,  0.,  7.,  9.],
       [ 2.,  4.,  6.,  2.,  3.,  9.,  4.,  5.,  9.,  5.,  1.,  4.]])

In [37]:
c[0,0]=111
a #可以看出来a发生了改变

array([[ 111.,    3.,    2.,    9.,    0.,    5.,    7.,    6.,    3.,
           0.,    7.,    9.],
       [   2.,    4.,    6.,    2.,    3.,    9.,    4.,    5.,    9.,
           5.,    1.,    4.]])

对array做切片的时候，实际上是一个view，因此不是一个copy，对它的修改会使得原矩阵改变

In [38]:
s = a[:,1:3]
s

array([[ 3.,  2.],
       [ 4.,  6.]])

In [39]:
s[:] = 100
a

array([[ 111.,  100.,  100.,    9.,    0.,    5.,    7.,    6.,    3.,
           0.,    7.,    9.],
       [   2.,  100.,  100.,    2.,    3.,    9.,    4.,    5.,    9.,
           5.,    1.,    4.]])

### Deep copy:拷贝，就不再相关了

In [40]:
d = a.copy()
d

array([[ 111.,  100.,  100.,    9.,    0.,    5.,    7.,    6.,    3.,
           0.,    7.,    9.],
       [   2.,  100.,  100.,    2.,    3.,    9.,    4.,    5.,    9.,
           5.,    1.,    4.]])

In [42]:
d is a  #拷贝，但是内存地址不同

False

In [43]:
d.base is a

False

In [47]:
d[0,0] = 999
a

array([[ 111.,  100.,  100.,    9.,    0.,    5.,    7.,    6.,    3.,
           0.,    7.,    9.],
       [   2.,  100.,  100.,    2.,    3.,    9.,    4.,    5.,    9.,
           5.,    1.,    4.]])

### 广播

### Fancy indexing
#### indexing with Arrays of indices

In [49]:
a = np.arange(12) ** 2
i = np.array([1,1,3,8,5])
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [50]:
a[i]

array([ 1,  1,  9, 64, 25])

In [51]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
j

array([[3, 4],
       [9, 7]])

In [53]:
a[j]  #按照j的格式取index

array([[ 9, 16],
       [81, 49]])

In [54]:
palette = np.array( [ [0,0,0],                # black
...                       [255,0,0],              # red
...                       [0,255,0],              # green
...                       [0,0,255],              # blue
...                       [255,255,255] ] )       # white

In [56]:
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [58]:
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
...                     [ 0, 3, 4, 0 ]  ] )
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [61]:
time = np.linspace(20, 145, 5) 
data = np.sin(np.arange(20)).reshape(5,4)
time,data

(array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ]),
 array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
        [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
        [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
        [-0.28790332, -0.96139749, -0.75098725,  0.14987721]]))

In [62]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [63]:
time_max = time[ind]
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

NameError: name 'xrange' is not defined

range(0, 4)