# 60 minutes Pytorch入门

## 一、get started

### 1.Tensors 张量
tensor可以做为numpy的替代品，同时更加可以发挥GPU的效果

In [2]:
from __future__ import print_function
import torch

In [8]:
# 新建一个矩阵
x = torch.Tensor(5, 3)
x


1.00000e-06 *
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000 -1.8205  0.0000
 -1.8030  0.0000  0.0000
[torch.FloatTensor of size 5x3]

In [16]:
# 随机阵
x = torch.rand(5, 3)
x


 0.6121  0.9248  0.0682
 0.8505  0.5923  0.9665
 0.5343  0.8030  0.3350
 0.5386  0.9845  0.3087
 0.7027  0.0525  0.0270
[torch.FloatTensor of size 5x3]

In [15]:
# 返回矩阵的维度, 很明显是一个tuple
x.size()

torch.Size([5, 3])

### 2. Operations
有许多中可以使用的语法

In [17]:
# 加法 1
y = torch.rand(5, 3)
x+y


 1.0093  1.6769  0.6121
 0.9485  0.8397  1.7615
 0.6230  1.7907  0.9541
 1.1451  1.9134  0.7431
 1.1964  0.4690  0.1547
[torch.FloatTensor of size 5x3]

In [18]:
# 加法 2
torch.add(x,y)


 1.0093  1.6769  0.6121
 0.9485  0.8397  1.7615
 0.6230  1.7907  0.9541
 1.1451  1.9134  0.7431
 1.1964  0.4690  0.1547
[torch.FloatTensor of size 5x3]

In [19]:
#  加法3：事先声明一个存储结果的tensor
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)



 1.0093  1.6769  0.6121
 0.9485  0.8397  1.7615
 0.6230  1.7907  0.9541
 1.1451  1.9134  0.7431
 1.1964  0.4690  0.1547
[torch.FloatTensor of size 5x3]

In [20]:
result


 1.0093  1.6769  0.6121
 0.9485  0.8397  1.7615
 0.6230  1.7907  0.9541
 1.1451  1.9134  0.7431
 1.1964  0.4690  0.1547
[torch.FloatTensor of size 5x3]

In [22]:
# 加法4 直接在自身做替代
# 即将x加到y上面，y = y + x
y.add_(x)
y


 1.6214  2.6017  0.6802
 1.7990  1.4320  2.7281
 1.1572  2.5938  1.2891
 1.6837  2.8978  1.0518
 1.8990  0.5214  0.1817
[torch.FloatTensor of size 5x3]

**注** ：每一个operation以_结尾的时候，都是在自身上做操作的

In [23]:
x


 0.6121  0.9248  0.0682
 0.8505  0.5923  0.9665
 0.5343  0.8030  0.3350
 0.5386  0.9845  0.3087
 0.7027  0.0525  0.0270
[torch.FloatTensor of size 5x3]

In [24]:
x.t_() #转置，x自身


 0.6121  0.8505  0.5343  0.5386  0.7027
 0.9248  0.5923  0.8030  0.9845  0.0525
 0.0682  0.9665  0.3350  0.3087  0.0270
[torch.FloatTensor of size 3x5]

In [25]:
x[:, 1]


 0.8505
 0.5923
 0.9665
[torch.FloatTensor of size 3]

In [26]:
x[1,]


 0.9248
 0.5923
 0.8030
 0.9845
 0.0525
[torch.FloatTensor of size 5]

In [29]:
x[1:2,] #和numpy类似


 0.9248  0.5923  0.8030  0.9845  0.0525
[torch.FloatTensor of size 1x5]

In [31]:
x[1,0:2]


 0.9248
 0.5923
[torch.FloatTensor of size 2]

### 3. Numpy Bridge
Numpy对象和torch中的Tensor会共享同样的内存地址，因此任何一个发生改变，另一个都会改变

+ 将torch Tensor转换为numpy Array

In [34]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [37]:
b = a.numpy() #numpy对象
print(b)

[ 1.  1.  1.  1.  1.]


In [38]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [39]:
# 可以看到b也发生了对应的变化
b

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

+ 将numpy Array转换为torch Tensor

In [40]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
a

array([ 1.,  1.,  1.,  1.,  1.])

In [41]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [42]:
np.add(a, 1, out=a)
a

array([ 2.,  2.,  2.,  2.,  2.])

In [43]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

### 4. cuda Tensors
tensors可以使用函数 `.cuda()`来将其移动到CPU中

In [44]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

## 二、Autograd:automatic differentiation
torch中的神经网络模型都是使用 `autograd` 包来进行微分计算

### Variables
`autograd.Variable` 包含了Tensor和其operation，当调用 `.backward()`时所有的梯度就会自动计算

可以通过 .data  属性来获取raw tensor ， grad累计进入 .grad

## function

function和variables是内在连接的，构成无环图 。 

In [57]:
import torch
from torch.autograd import Variable

In [58]:
# create a variable
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [59]:
x.type

<bound method Variable.type of Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]
>

In [62]:
y = x + 2
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [64]:
y.creator

In [66]:
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [76]:
z = y * y * 3
out = z.mean()
out

Variable containing:
 27
[torch.FloatTensor of size 1]

### Gradients


In [72]:
out.backward()

In [73]:
out

Variable containing:
 27
[torch.FloatTensor of size 1]

In [75]:
print(x.grad)

Variable containing:
 9  9
 9  9
[torch.FloatTensor of size 2x2]

