# 60 minutes Pytorch入门

## 一、get started

### 1.Tensors 张量
tensor可以做为numpy的替代品，同时更加可以发挥GPU的效果

In [1]:
from __future__ import print_function
import torch

In [2]:
# 新建一个矩阵
x = torch.Tensor(5, 3)
x


1.00000e-10 *
 -1.8972  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]

In [3]:
# 随机阵
x = torch.rand(5, 3)
x


 0.6245  0.6275  0.7128
 0.5102  0.3600  0.6426
 0.8362  0.7604  0.4615
 0.6427  0.5060  0.5446
 0.8391  0.1200  0.9095
[torch.FloatTensor of size 5x3]

In [4]:
# 返回矩阵的维度, 很明显是一个tuple
x.size()

torch.Size([5, 3])

### 2. Operations
有许多中可以使用的语法

In [5]:
# 加法 1
y = torch.rand(5, 3)
x+y


 0.7058  1.5629  1.2636
 1.3640  0.4889  1.1104
 0.9645  1.1970  1.1245
 1.0465  1.0298  1.1443
 0.9756  1.0478  1.0549
[torch.FloatTensor of size 5x3]

In [6]:
# 加法 2
torch.add(x,y)


 0.7058  1.5629  1.2636
 1.3640  0.4889  1.1104
 0.9645  1.1970  1.1245
 1.0465  1.0298  1.1443
 0.9756  1.0478  1.0549
[torch.FloatTensor of size 5x3]

In [7]:
#  加法3：事先声明一个存储结果的tensor
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)



 0.7058  1.5629  1.2636
 1.3640  0.4889  1.1104
 0.9645  1.1970  1.1245
 1.0465  1.0298  1.1443
 0.9756  1.0478  1.0549
[torch.FloatTensor of size 5x3]

In [8]:
result


 0.7058  1.5629  1.2636
 1.3640  0.4889  1.1104
 0.9645  1.1970  1.1245
 1.0465  1.0298  1.1443
 0.9756  1.0478  1.0549
[torch.FloatTensor of size 5x3]

In [9]:
# 加法4 直接在自身做替代
# 即将x加到y上面，y = y + x
y.add_(x)
y


 0.7058  1.5629  1.2636
 1.3640  0.4889  1.1104
 0.9645  1.1970  1.1245
 1.0465  1.0298  1.1443
 0.9756  1.0478  1.0549
[torch.FloatTensor of size 5x3]

**注** ：每一个operation以_结尾的时候，都是在自身上做操作的

In [10]:
x


 0.6245  0.6275  0.7128
 0.5102  0.3600  0.6426
 0.8362  0.7604  0.4615
 0.6427  0.5060  0.5446
 0.8391  0.1200  0.9095
[torch.FloatTensor of size 5x3]

In [11]:
x.t_() #转置，x自身


 0.6245  0.5102  0.8362  0.6427  0.8391
 0.6275  0.3600  0.7604  0.5060  0.1200
 0.7128  0.6426  0.4615  0.5446  0.9095
[torch.FloatTensor of size 3x5]

In [12]:
x[:, 1]


 0.5102
 0.3600
 0.6426
[torch.FloatTensor of size 3]

In [13]:
x[1,]


 0.6275
 0.3600
 0.7604
 0.5060
 0.1200
[torch.FloatTensor of size 5]

In [14]:
x[1:2,] #和numpy类似


 0.6275  0.3600  0.7604  0.5060  0.1200
[torch.FloatTensor of size 1x5]

In [15]:
x[1,0:2]


 0.6275
 0.3600
[torch.FloatTensor of size 2]

### 3. Numpy Bridge
Numpy对象和torch中的Tensor会共享同样的内存地址，因此任何一个发生改变，另一个都会改变

+ 将torch Tensor转换为numpy Array

In [16]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [17]:
b = a.numpy() #numpy对象
print(b)

[ 1.  1.  1.  1.  1.]


In [18]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [19]:
# 可以看到b也发生了对应的变化
b

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

+ 将numpy Array转换为torch Tensor

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
a

array([ 1.,  1.,  1.,  1.,  1.])

In [21]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [22]:
np.add(a, 1, out=a)
a

array([ 2.,  2.,  2.,  2.,  2.])

In [23]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

### 4. cuda Tensors
tensors可以使用函数 `.cuda()`来将其移动到CPU中

In [24]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

## 二、Autograd:automatic differentiation
torch中的神经网络模型都是使用 `autograd` 包来进行微分计算

### Variables
`autograd.Variable` 包含了Tensor和其operation，当调用 `.backward()`时所有的梯度就会自动计算

可以通过 .data  属性来获取raw tensor ， grad累计进入 .grad

## function

function和variables是内在连接的，构成无环图 。 

In [25]:
import torch
from torch.autograd import Variable

In [26]:
# create a variable
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [27]:
x.type

<bound method Variable.type of Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]
>

In [28]:
y = x + 2
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [29]:
y.creator

In [30]:
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [31]:
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



### Gradients
out.backward()就相当于out.backward(torch.Tensor([1.0]))

In [32]:
out.backward()

In [33]:
out

Variable containing:
 27
[torch.FloatTensor of size 1]

In [34]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



这上面的式子是Variable O可以表示为$ O = \frac{1}{4} \sum_i{z_i}, 其中z_i = 3(x_i^2 + 2)^2$， 有$z_i|_{x_i=1}=27$,倒数为$\frac{\partial o}{\partial x_i}=\frac{3}{2}(x_i+2)$, 在$x_i=1$处的导数就是4.5。

In [42]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x*2

In [43]:
x

Variable containing:
-0.4834
-0.5751
 0.0437
[torch.FloatTensor of size 3]

In [45]:
while y.data.norm( ) < 1000:
    y = y *2
    z = y ** 2
    
print(y)

Variable containing:
 -990.0595
-1177.8800
   89.4755
[torch.FloatTensor of size 3]



In [48]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
z.backward(gradients) #在这个向量处求梯度

print(x.grad)

Variable containing:
-4.0532e+05
-4.8225e+06
 3.6854e+01
[torch.FloatTensor of size 3]



## 三、神经网络


In [52]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

In [54]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net (
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear (400 -> 120)
  (fc2): Linear (120 -> 84)
  (fc3): Linear (84 -> 10)
)


只需要自定义forward函数，而不需要定义backward函数。
可学习的参数可以 通过 net.parameters()返回

In [57]:
params = list(net.parameters())
print(len(params),'\n', params[0].size())   

10 
 torch.Size([6, 1, 5, 5])
