In [1]:
%load_ext watermark

In [2]:
%watermark -v -d -p sklearn,matplotlib,numpy,pandas

2017-07-20 

CPython 2.7.13
IPython 5.4.1

sklearn 0.18.1
matplotlib 2.0.2
numpy 1.12.1
pandas 0.20.2


# K Nearest Neighbors
KNN算法，sklearn文章位置 user guide -> 1.6

周围k个近邻的label来vote

$$y=arg\underset{c_j}{max}\underset{x_i \in N_k(x))}{\sum}I(y_i=c_j))$$



## 分类决策规则
通常采取投票表决即vote的形式；

设分类的损失函数为0-1函数

经验损失函数 $1-\frac{1}{N}\underset{x_i \in N_k(x))}{\sum}I(y_i=c_j))$最小，即上式子最大。
因此，vote等价于经验风险最小化

## sklearn的实现
['auto', 'ball_tree', 'kd_tree', 'brute']

In [4]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]])

In [5]:
distances

array([[ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.41421356],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.41421356]])

In [6]:
nbrs.kneighbors_graph(X).toarray()

array([[ 1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.]])