# numpy exercises
from github [https://github.com/Kyubyong/numpy_exercises](https://github.com/Kyubyong/numpy_exercises)

测试一下numpy功能是否学会

## Array Creation

In [1]:
import numpy as np
np.zeros([2,2], dtype = np.int32)

array([[0, 0],
       [0, 0]], dtype=int32)

In [2]:
X = np.array([[1,2,3],[4,5,6]], np.int32)
X

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [3]:
np.empty_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [4]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
X = np.arange(4, dtype=np.int64)
X

array([0, 1, 2, 3])

In [7]:
np.ones_like(X)

array([1, 1, 1, 1])

In [8]:
np.zeros([3,2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [9]:
np.ones([2,5]) * 6

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]])

In [10]:
# np.full 所有的元素是同一个值
np.full((2,5), 6, dtype = np.uint32)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [11]:
np.full_like(X, 6, dtype = np.int64)

array([6, 6, 6, 6])

In [12]:
np.array([1,2,3])

array([1, 2, 3])

In [13]:
x = [1,2]
np.array(x)

array([1, 2])

In [14]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [15]:
np.matrix(X)

matrix([[1, 2],
        [3, 4]])

In [16]:
type(np.matrix(X))

numpy.matrixlib.defmatrix.matrix

In [17]:
np.array(x, dtype=np.float64)

array([ 1.,  2.])

In [18]:
x = np.array([30])
# convert it to scalar
np.asscalar(x)

30

In [19]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [20]:
y = x.copy()
y

array([1, 2, 3])

In [21]:
id(y) == id(x)

False

In [22]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [23]:
np.linspace(3., 10.0, 50)

array([  3.        ,   3.14285714,   3.28571429,   3.42857143,
         3.57142857,   3.71428571,   3.85714286,   4.        ,
         4.14285714,   4.28571429,   4.42857143,   4.57142857,
         4.71428571,   4.85714286,   5.        ,   5.14285714,
         5.28571429,   5.42857143,   5.57142857,   5.71428571,
         5.85714286,   6.        ,   6.14285714,   6.28571429,
         6.42857143,   6.57142857,   6.71428571,   6.85714286,
         7.        ,   7.14285714,   7.28571429,   7.42857143,
         7.57142857,   7.71428571,   7.85714286,   8.        ,
         8.14285714,   8.28571429,   8.42857143,   8.57142857,
         8.71428571,   8.85714286,   9.        ,   9.14285714,
         9.28571429,   9.42857143,   9.57142857,   9.71428571,
         9.85714286,  10.        ])

In [24]:
np.logspace(3., 10., 50)

array([  1.00000000e+03,   1.38949549e+03,   1.93069773e+03,
         2.68269580e+03,   3.72759372e+03,   5.17947468e+03,
         7.19685673e+03,   1.00000000e+04,   1.38949549e+04,
         1.93069773e+04,   2.68269580e+04,   3.72759372e+04,
         5.17947468e+04,   7.19685673e+04,   1.00000000e+05,
         1.38949549e+05,   1.93069773e+05,   2.68269580e+05,
         3.72759372e+05,   5.17947468e+05,   7.19685673e+05,
         1.00000000e+06,   1.38949549e+06,   1.93069773e+06,
         2.68269580e+06,   3.72759372e+06,   5.17947468e+06,
         7.19685673e+06,   1.00000000e+07,   1.38949549e+07,
         1.93069773e+07,   2.68269580e+07,   3.72759372e+07,
         5.17947468e+07,   7.19685673e+07,   1.00000000e+08,
         1.38949549e+08,   1.93069773e+08,   2.68269580e+08,
         3.72759372e+08,   5.17947468e+08,   7.19685673e+08,
         1.00000000e+09,   1.38949549e+09,   1.93069773e+09,
         2.68269580e+09,   3.72759372e+09,   5.17947468e+09,
         7.19685673e+09,

In [25]:
X = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.diag(X)

array([ 0,  5, 10])

In [27]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.tri(3,5,-1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [29]:
np.tril(np.arange(1,13).reshape(4,3), -1) # 下三角

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [30]:
np.triu(np.arange(1,13).reshape(4,3), -1) # 上三角

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [31]:
np.asscalar

<function numpy.lib.type_check.asscalar>

### 总结
+ np.asscalar:转换为标量
+ np.logspace:对数序列
+ np.tri：第几个对角元以下为1，其余为0
+ np.tril:下三角
+ np.triu:上三角

## array manipulation

In [32]:
x = np.zeros([10,10,3])
x.reshape([-1, 150])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       

In [33]:
?np.allclose

In [34]:
x = np.array([[1,2,3],[4,5,6]])
x.reshape([1,-1],order='F')

array([[1, 4, 2, 5, 3, 6]])

In [35]:
x.ravel(order='F')

array([1, 4, 2, 5, 3, 6])

In [36]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x.ravel()[4]

5

In [38]:
y = np.random.randn(3,4)
y.transpose()

array([[-0.47888197, -2.03208898,  0.96191861],
       [-0.28018778, -1.03963724,  0.46605104],
       [ 0.5758372 , -0.83472885, -0.22682814],
       [ 1.46687117, -0.14893082,  0.7750677 ]])

In [39]:
y.swapaxes(1,0)

array([[-0.47888197, -2.03208898,  0.96191861],
       [-0.28018778, -1.03963724,  0.46605104],
       [ 0.5758372 , -0.83472885, -0.22682814],
       [ 1.46687117, -0.14893082,  0.7750677 ]])

In [40]:
y

array([[-0.47888197, -0.28018778,  0.5758372 ,  1.46687117],
       [-2.03208898, -1.03963724, -0.83472885, -0.14893082],
       [ 0.96191861,  0.46605104, -0.22682814,  0.7750677 ]])

In [41]:
y[:,np.newaxis,:].shape

(3, 1, 4)

In [42]:
y[:,np.newaxis,:]

array([[[-0.47888197, -0.28018778,  0.5758372 ,  1.46687117]],

       [[-2.03208898, -1.03963724, -0.83472885, -0.14893082]],

       [[ 0.96191861,  0.46605104, -0.22682814,  0.7750677 ]]])

In [43]:
np.expand_dims(x, axis = 1).shape

(2, 1, 3)

In [44]:
x=np.zeros([2,3,1])
x.squeeze().shape

(2, 3)

In [45]:
np.squeeze(x).shape

(2, 3)

In [46]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
print x,'\n',y

[[1]
 [2]
 [3]] 
[[4]
 [5]
 [6]]


In [47]:
np.dstack((x,y))

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

In [48]:
x = np.array([0,1,2])
np.repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

In [49]:
x = np.array((0,0,0,1,2,3,0,2,1,0))
x

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [50]:
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])

In [54]:
x = np.random.randn(3,3)
x

array([[ 1.45882882,  1.16238179,  0.48510596],
       [ 0.68684527, -0.57774512, -1.49008876],
       [-0.27244762, -1.34588262, -1.62642033]])

In [55]:
np.fliplr(x) # 左右调转

array([[ 0.48510596,  1.16238179,  1.45882882],
       [-1.49008876, -0.57774512,  0.68684527],
       [-1.62642033, -1.34588262, -0.27244762]])

In [56]:
np.flipud(x) # 上下翻转

array([[-0.27244762, -1.34588262, -1.62642033],
       [ 0.68684527, -0.57774512, -1.49008876],
       [ 1.45882882,  1.16238179,  0.48510596]])

In [58]:
x = np.array([[1,2,3],[4,5,3]])
print x
np.rot90(x) # 逆时针旋转90度

[[1 2 3]
 [4 5 3]]


array([[3, 3],
       [2, 5],
       [1, 4]])

###  总结
+ np.repeat
+ np.squeeze
+ np.swapaxes
+ np.fliplr, np.flipud
+ np.rot90, np.roll

In [62]:
np.roll(np.arange(12), 3)

array([ 9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [63]:
x

array([[1, 2, 3],
       [4, 5, 3]])

In [65]:
np.roll(x, 1, axis = 0)

array([[4, 5, 3],
       [1, 2, 3]])

In [66]:
np.roll(x, 1, axis = 1)

array([[3, 1, 2],
       [3, 4, 5]])

## LInear algebra
线性代数计算部分测试


### matrix and vector products
**划重点**：
关于numpy中的array对象，其实它还是很强大的，不能因为和matlab和R之间的一些些区别，而去否认它的作用。下面是一些容易混淆的地方：

+ 关于乘法
 + array操作中 * 表示的是element的点乘，而dot才是类似矩阵乘法的操作；
 + matrix这种对象，是numpy中为了方便linear algebra操作而引入的类型；其中*是它的矩阵乘法操作，而multiply则是它的element点乘操作

+ 关于向量
 + 对于Array来说，$1\times N, N \times 1, N$是不同的；A[:,1]返回的一般是一个shape为N的向量，不是一个二维array($N\times 1$这种)，而是shape为(N,)，即使转置也并没有用。
 + matrix以上这样会返回一个二维的矩阵
 
+ 在与向量做乘法时，dot(A,v)将v作为一个列向量,dot(v,A)将v作为一个行向量

In [67]:
x = [1,2]
y = [[4,1], [2,2]]
x

[1, 2]

In [68]:
y

[[4, 1], [2, 2]]

In [74]:
np.dot(x, y)

(2,)

In [72]:
np.dot(y, x)

array([6, 6])

In [83]:
x=np.array([2,3,4,1]) 
# 仅仅是一个数组，只有一个维度；行向量
x.shape

(4,)

In [85]:
y=x.reshape(-1,1) # 变成一个列向量

print y.shape
y

(4, 1)


array([[2],
       [3],
       [4],
       [1]])

In [86]:
x[:,np.newaxis]

array([[2],
       [3],
       [4],
       [1]])

In [93]:
np.c_[x]

array([[2],
       [3],
       [4],
       [1]])

In [106]:
np.arange(1,7).reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
np.arange(1,7).reshape(-1,2).transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [108]:
a = np.arange(1,7).reshape(2,-1)
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [110]:
a.flatten(order='F')  # 按列展开

array([1, 4, 2, 5, 3, 6])

In [116]:
x = np.arange(2)
x

array([0, 1])

In [117]:
x.shape # 向量

(2,)

In [121]:
y = np.array([[1,2],[3,1]])
print y.shape
y

(2, 2)


array([[1, 2],
       [3, 1]])

In [122]:
z = x * y  # 广播
print z.shape
z

(2, 2)


array([[0, 2],
       [0, 1]])

In [123]:
y * x

array([[0, 2],
       [0, 1]])

In [125]:
temp1 = np.dot(x, y) # 行向量
print temp1.shape
temp1

(2,)


array([3, 1])

In [126]:
temp2 = np.dot(y, x) # 行向量
print temp2.shape
temp2

(2,)


array([2, 1])

In [131]:
type(x.transpose())

numpy.ndarray

In [132]:
type(x)

numpy.ndarray

In [140]:
x = [1,2]
y = [[4, 1], [2, 2]]
print np.dot(x, y)
print np.dot(y, x)
print np.matmul(x, y)
print np.matmul(y,x)
print np.inner(x, y)
print np.inner(y, x)

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]
[6 6]


In [142]:
np.dot(y,x).shape

(2,)

In [135]:
x = np.array(x)

In [136]:
x

array([1, 2])

In [139]:
x[:,]

array([1, 2])

In [143]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a[:,0].shape

(2,)

In [150]:
a[:,0]

array([1, 4])

In [146]:
A = np.matrix(a)

In [147]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [149]:
A[:,0].shape

(2, 1)

In [151]:
A[:,0]

matrix([[1],
        [4]])

In [154]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
a[np.array([[0,0,0],[1,1,1]])]

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]])

In [182]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print np.inner(x, y)
print np.inner(y, x)
print np.outer(x, y)
print np.outer(y, x)

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


### Decompositions矩阵分解

In [185]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
L

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [186]:
# qr分解
q,r = np.linalg.qr(x)
print q
print r

[[-0.19611614 -0.16947544  0.96582428]
 [-0.58834841 -0.76762404 -0.25416428]
 [ 0.78446454 -0.61808689  0.05083286]]
[[ -20.39607805  -57.85425987  105.31436457]
 [   0.           -3.8580585   -24.85307452]
 [   0.            0.            0.45749571]]


In [188]:
# svd 奇异值分解
U, s, V = np.linalg.svd(x, full_matrices=False)
print U,'\n',s,'\n', V

[[-0.16300693 -0.21272739  0.96341881]
 [-0.45732393 -0.84895218 -0.26483016]
 [ 0.87423313 -0.48376363  0.04109976]] 
[  1.23477232e+02   1.55039632e+01   1.88049805e-02] 
[[-0.16300693 -0.45732393  0.87423313]
 [-0.21272739 -0.84895218 -0.48376363]
 [ 0.96341881 -0.26483016  0.04109976]]


### 特征值

In [192]:
x = np.diag((1, 2, 3))
np.linalg.eig(x)[0] # 特征值

array([ 1.,  2.,  3.])

In [193]:
np.linalg.eig(x)[1:] # 特征向量

(array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]),)

In [196]:
np.linalg.eigvals(x) # 只返回特征值

array([ 1.,  2.,  3.])

### 范数

In [197]:
x = np.arange(1,10).reshape((3,3))
print np.linalg.norm(x, 'fro') # Frobenius norm
print np.linalg.cond(x, 'fro')


16.8819430161
3.19323951562e+17


In [199]:
# det
np.linalg.det(x)

-9.5161973539299405e-16

In [200]:
np.linalg.matrix_rank(x)

2

In [201]:
np.trace(x)

15

### 逆矩阵

In [202]:
np.linalg.inv(x)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

## logic functions


In [2]:
import numpy as np
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [3]:
np.all(x)

True

In [4]:
x = np.array([0,1,3])
print np.any(x)
x

True


array([0, 1, 3])

In [6]:
x = np.array([1,0,np.nan, np.inf])
x

array([  1.,   0.,  nan,  inf])

In [7]:
np.isfinite(x)

array([ True,  True, False, False], dtype=bool)

In [10]:
np.isnan(x)

array([False, False,  True, False], dtype=bool)

In [11]:
np.isinf(x)

array([False, False, False,  True], dtype=bool)

In [12]:
x =np.array([1+1j, 1+0j, 4.5, 3, 2, 1])
x

array([ 1.0+1.j,  1.0+0.j,  4.5+0.j,  3.0+0.j,  2.0+0.j,  1.0+0.j])

In [13]:
np.iscomplex(x)

array([ True, False, False, False, False, False], dtype=bool)

In [14]:
np.isreal(x)

array([False,  True,  True,  True,  True,  True], dtype=bool)

In [16]:
print np.isscalar(3), np.isscalar([3]),np.isscalar(True)

True False True


In [17]:
np.logical_and([True, False], [False, False])

array([False, False], dtype=bool)

In [18]:
np.logical_or([True, False], [False, False])

array([ True, False], dtype=bool)

In [21]:
x = np.array([4,5])
y = np.array([2,5])
np.greater_equal(x,y)

array([ True,  True], dtype=bool)

In [22]:
np.greater(x,y)

array([ True, False], dtype=bool)

In [23]:
np.equal([1,2],[1,2.0000])

array([ True,  True], dtype=bool)

In [24]:
np.isclose([1,2],[1,2.0000])

array([ True,  True], dtype=bool)

### 总结
+ np.greater, np.greater_equal >和>=

## help functions

### lookfor
搜寻关于某一个 功能描述 的函数

In [27]:
np.lookfor('linear algebra')

Search results for 'linear algebra'
-----------------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.restoredot
    Restore `dot`, `vdot`, and `innerproduct` to the default non-BLAS
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
numpy.linalg.cond
    Compute the condition number of a matrix.
numpy.linalg.eigh
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.LinAlgError
    Generic Python-exception-derived object raised by linalg functions.


In [33]:
np.lookfor('linear', module='pandas') # 指定某一个模块中搜索关键词

Search results for 'linear'
---------------------------
Nothing found.


### np.info
得到某一个函数的help文档

In [34]:
np.info(np.linalg.eig)

 eig(a)

Compute the eigenvalues and right eigenvectors of a square array.

Parameters
----------
a : (..., M, M) array
    Matrices for which the eigenvalues and right eigenvectors will
    be computed

Returns
-------
w : (..., M) array
    The eigenvalues, each repeated according to its multiplicity.
    The eigenvalues are not necessarily ordered. The resulting
    array will be of complex type, unless the imaginary part is
    zero in which case it will be cast to a real type. When `a`
    is real the resulting eigenvalues will be real (0 imaginary
    part) or occur in conjugate pairs

v : (..., M, M) array
    The normalized (unit "length") eigenvectors, such that the
    column ``v[:,i]`` is the eigenvector corresponding to the
    eigenvalue ``w[i]``.

Raises
------
LinAlgError
    If the eigenvalue computation does not converge.

See Also
--------
eigvals : eigenvalues of a non-symmetric array.

eigh : eigenvalues and eigenvectors of a symmetric or Hermitian
       (conjugate

## random sampling 随机抽样

### 随机数产生

In [35]:
np.random.rand(3,2) # (0,1)均匀分布

array([[ 0.69718078,  0.04174178],
       [ 0.20633766,  0.92262835],
       [ 0.25875241,  0.27517727]])

In [39]:
np.random.random([3,2])

array([[ 0.34593039,  0.50796963],
       [ 0.62028392,  0.7881214 ],
       [ 0.82022849,  0.02957116]])

In [40]:
np.random.randn(2,3)  # 标准正态分布

array([[ 0.31573997, -0.61746217,  2.38558409],
       [-1.12453309,  0.65142164,  0.14908193]])

In [42]:
np.random.normal(0,1,(2,3)) # 正态分布

array([[-1.39428874,  0.15204098,  0.3344671 ],
       [ 0.746265  , -0.40602983,  0.50443247]])

In [45]:
# discrete uniform distribution
np.random.randint(2, 5, (3,2))

array([[3, 2],
       [2, 3],
       [3, 3]])

In [50]:
# 按照概率抽取
x = ['0.5', '0.2', '0.3']
for _ in range(10):
    print np.random.choice(x, p = [.5, .2, .3])

0.5
0.2
0.5
0.2
0.5
0.5
0.5
0.5
0.5
0.5


In [52]:
np.random.choice(10, 3, replace=False)

array([8, 9, 0])

### permutation


In [54]:
np.random.permutation(np.arange(10))

array([2, 0, 1, 9, 5, 4, 3, 7, 6, 8])

In [57]:
# 或者是 np.random.shuffle,这事一个inplace操作
x = np.arange(10)
np.random.shuffle(x)
x

array([4, 8, 2, 1, 6, 7, 9, 5, 0, 3])

### seed随机种子的产生


In [58]:
#np.random.seed(1)

### 总结
+ np.random.rand:标准均匀分布;np.random.uniform普通均匀分布
+ np.random.randn:标准正态分布
+ np.random.normal:普通正态分布
+ np.random.randint:离散均匀分布
+ np.random.choice:按照某一指定的概率分布来随机抽样
+ np.random.permutation: permutation
+ np.random.shuffle:in-place 的permutation操作。
+ 种子:np.random.seed

## Set routines

In [61]:
x = np.array([1,2,6,4,2,2,3,2])
out, indices = np.unique(x, return_inverse=True)

In [62]:
out

array([1, 2, 3, 4, 6])

In [63]:
indices

array([0, 1, 4, 3, 1, 1, 2, 1])

In [64]:
x

array([1, 2, 6, 4, 2, 2, 3, 2])

In [66]:
np.unique(x, return_index=True)

(array([1, 2, 3, 4, 6]), array([0, 1, 6, 3, 2]))

In [70]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 6]), array([1, 4, 1, 1, 1]))

### bool
+ 判断x中的任意元素是不是在与中

In [73]:
x = np.array([0,1,2,5,0])
y = np.array([0,1])
np.in1d(x,y)

array([ True,  True, False, False,  True], dtype=bool)

In [74]:
np.in1d(y,x)

array([ True,  True], dtype=bool)

In [75]:
# 交集
np.intersect1d(x,y)

array([0, 1])

In [76]:
# x中独有的
np.setdiff1d(x, y)

array([2, 5])

In [77]:
np.setdiff1d(y,x)

array([], dtype=int64)

In [78]:
# 并集
np.union1d(x,y)

array([0, 1, 2, 5])

### 总结
+ 关于np.unique函数
return_index返回的是unique完之后的数组在原来的数组中的index
return_inverse返回的是可以通过out按照此index inverse回原来的数组
return_counts同样返回每一个元素出现的次数

## sorting , searching, couting

### sorting


In [79]:
x = np.array([[1,4],[3,1]])
x

array([[1, 4],
       [3, 1]])

In [80]:
np.sort(x, axis=1)

array([[1, 4],
       [1, 3]])

In [81]:
surnames = ('hertiz','gal','hertiz')
first_names = ('Herinch','Galileo','Gustav')
np.lexsort((first_names, surnames))
# 先使用第二个作为key，再使用第一个作为key

array([1, 2, 0])

In [83]:
np.argsort(x)

array([[0, 1],
       [1, 0]])

In [85]:
x = np.random.permutation(10)
x

array([3, 1, 8, 2, 9, 5, 7, 4, 6, 0])

In [86]:
np.partition(x, 5)

array([2, 0, 1, 3, 4, 5, 6, 7, 8, 9])

### searching

In [87]:
# 不考虑nan
np.nanargmax(x)

4

In [88]:
x = [1,3,5,7,9]
y = [0,4,2,6]
np.searchsorted(x,y)
# 返回y被插入到x中时，index所在的位置

array([0, 2, 1, 3])

In [89]:
x = np.random.randn(2,3)
x

array([[ 0.91642285, -1.80607774, -0.55082994],
       [-0.19821148,  0.36891056,  0.28014486]])

In [91]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [92]:
np.count_nonzero(x)

6

In [96]:
np.where(x != 0)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))